version: '2'

services:
    nginx:
        build: docker/nginx
        ports:
            - 81:80
        links:
            - php
        volumes_from:
            - php
        environment:
            APP_SERVER_NAME: 192.168.99.100

    php:
        build: docker/php
        ports:
            - 9000:9000
        volumes:
            - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            - /var/www/html

    lb:
        image: abiosoft/caddy
        depends_on:
            - php
        ports:
            - 2015:2015
            - 443:443
            - 80:80
        volumes:
            - ./docker/caddy/Caddyfile:/etc/Caddyfile
            - ./docker/caddy/certs:/root/.caddy
        command: --conf /etc/Caddyfile --log stdout -email mathias@zenfitapp.com -agree
