<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true, 'test' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    AppBundle\AppBundle::class => ['all' => true],
    LenusBundle\LenusBundle::class => ['all' => true],
    FOS\UserBundle\FOSUserBundle::class => ['all' => true],
    Zenfit\PhotoUploaderBundle\ZenfitPhotoUploaderBundle::class => ['all' => true],
    Zenfit\StripeBundle\ZenfitStripeBundle::class => ['all' => true],
    Zenfit\UserBundle\ZenfitUserBundle::class => ['all' => true],
    ReactApiBundle\ReactApiBundle::class => ['all' => true],
    SunCat\MobileDetectBundle\MobileDetectBundle::class => ['all' => true],
    EmailBundle\EmailBundle::class => ['all' => true],
    WorkoutPlanBundle\WorkoutPlanBundle::class => ['all' => true],
    TrainerBundle\TrainerBundle::class => ['all' => true],
    MealBundle\MealBundle::class => ['all' => true],
    ClientBundle\ClientBundle::class => ['all' => true],
    ExerciseBundle\ExerciseBundle::class => ['all' => true],
    ChatBundle\ChatBundle::class => ['all' => true],
    Http\HttplugBundle\HttplugBundle::class => ['all' => true],
    VideoBundle\VideoBundle::class => ['all' => true],
    Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle::class => ['all' => true],
    AdminBundle\AdminBundle::class => ['all' => true],
    ProgressBundle\ProgressBundle::class => ['all' => true],
    LeadBundle\LeadBundle::class => ['all' => true],
    GymBundle\GymBundle::class => ['all' => true],
    Nelmio\CorsBundle\NelmioCorsBundle::class => ['all' => true],
    Aws\Symfony\AwsBundle::class => ['all' => true],
    Knp\Bundle\TimeBundle\KnpTimeBundle::class => ['all' => true],
    ZapierBundle\ZapierBundle::class => ['all' => true],
    ApiBundle\ApiBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    PlanBundle\PlanBundle::class => ['all' => true],
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],
    Elao\Enum\Bridge\Symfony\Bundle\ElaoEnumBundle::class => ['all' => true],
    Sentry\SentryBundle\SentryBundle::class => ['all' => true],
    DAMA\DoctrineTestBundle\DAMADoctrineTestBundle::class => ['test' => true],
    Lexik\Bundle\JWTAuthenticationBundle\LexikJWTAuthenticationBundle::class => ['all' => true],
    Gesdinet\JWTRefreshTokenBundle\GesdinetJWTRefreshTokenBundle::class => ['all' => true],
];
