security:
    enable_authenticator_manager: true

    encoders:
        bcryptEncoder:
            algorithm: bcrypt
            cost: 15
        FOS\UserBundle\Model\UserInterface: auto

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        refresh:
            pattern:  ^/token/refresh$
            stateless: true
            refresh_jwt: ~

        login:
            pattern: ^/login
            stateless: true
            json_login:
                check_path: login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            pattern:   ^/
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

            logout:
                path: fos_user_security_logout
                target: /login
                invalidate_session: true
                delete_cookies: ['BEARER', 'REFRESH_TOKEN']

    access_control:
        - { path: ^/token/refresh, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin/gecko, roles: PUBLIC_ACCESS }
        - { path: ^/admin/recipes, roles: ROLE_ADMIN }
        - { path: ^/admin/api/recipes, roles: ROLE_ADMIN }
        - { path: ^/admin/recipe-children, roles: ROLE_ADMIN }
        - { path: ^/admin/ingredients, roles: ROLE_ADMIN }
        - { path: ^/admin/api/ingredients, roles: ROLE_ADMIN }
        - { path: ^/admin/api/clients, roles: ROLE_ADMIN }
        - { path: ^/admin/clients, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_SUPER_ADMIN }
        - { path: ^/lenus, role: PUBLIC_ACCESS }
        - { path: ^/hook/, role: PUBLIC_ACCESS }
        - { path: ^/mfp/, role: PUBLIC_ACCESS }
        - { path: ^/api/client/updateClientInfo, role: PUBLIC_ACCESS }
        - { path: ^/api/client/uploadImg, role: PUBLIC_ACCESS }
        - { path: ^/checkout/, role: PUBLIC_ACCESS }
        - { path: ^/trainer/leadCreateQuery, role: PUBLIC_ACCESS }
        - { path: ^/sign-up, role: PUBLIC_ACCESS }
        - { path: ^/new-password, role: PUBLIC_ACCESS }
        - { path: ^/resetting, role: PUBLIC_ACCESS }
        - { path: ^/client/login, role: PUBLIC_ACCESS }
        - { path: ^/client/settings, role: PUBLIC_ACCESS }
        - { path: ^/client/create-session, role: PUBLIC_ACCESS }
        - { path: ^/client/logout, role: PUBLIC_ACCESS }
        - { path: ^/client/forgot-password, role: PUBLIC_ACCESS }
        - { path: ^/client/confirm-unsubscription, role: PUBLIC_ACCESS }
        - { path: ^/client/request-unsubscribe, role: PUBLIC_ACCESS }
        - { path: ^/client/delete, role: PUBLIC_ACCESS }
        - { path: ^/client/clientActivation, role: PUBLIC_ACCESS }
        - { path: ^/react-api/, role: PUBLIC_ACCESS }
        - { path: ^/zapier, role: PUBLIC_ACCESS }
        - { path: ^/gym/, role: PUBLIC_ACCESS }
        - { path: ^/email/callback, role: PUBLIC_ACCESS }
        - { path: ^/leads/survey/, role: PUBLIC_ACCESS }
        - { path: ^/auth/api/, role: PUBLIC_ACCESS }
        - { path: ^/dashboard/leads, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/dashboard/clients, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/dashboard/clientOverview, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/dashboard/chatOverview, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/client/info, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/meal, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/video/api/add-video-to-client, methods: [POST], roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/dashboard/addVideoToClient, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/dashboard/deleteVideoToClient, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/progress/client, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/progress/api/addRecord, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/dashboard/clientDocuments, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/dashboard/addDocumentToClient, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/dashboard/documentOverview, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/dashboard/uploadDocument, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/dashboard/deleteDocument, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/dashboard/deleteDocumentToClient, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/dashboard/deleteVideoToClient, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/dashboard/clientVideos, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/dashboard/mealProducts, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/dashboard$, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/internal-api/products, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/workout, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/exercises/user-exercises, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/progress, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/pdf/exportPlansPdfMealClient, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/api/clients/count, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/api/news, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/chat/overview, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/chat/api, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/leads/api, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/api/trainer/get-lead-tags-by-user, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/api/recipe/get-recipes, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/api/meal/plans, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/api/meal/save, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/api/trainer/get-default-messages, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/api/clients, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/api/client/add, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/api/client/settings/set-client-settings, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/api/trainer/send-email-to-client, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/api/exercises, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/api/workout/client/.+/days, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/api/workout/client/save-workout, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/api/v3/meal, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/api/trainer/clients, roles: [ROLE_TRAINER, ROLE_ASSISTANT] }
        - { path: ^/, role: ROLE_TRAINER }
