AppBundle\Entity\Equipment:
        type: entity
        table: equipments
        repositoryClass: AppBundle\Repository\EquipmentRepository
        id:
            id:
                type: integer
                id: true
                generator:
                    strategy: AUTO
                options:
                    unsigned: true

        fields:

            name:
                type: string
                length: 255

        oneToMany:
            exercises:
                targetEntity: AppBundle\Entity\Exercise
                mappedBy: equipment
                cache:
                    usage: NONSTRICT_READ_WRITE
