AppBundle\Entity\ExerciseType:
    type: entity
    table: exercise_types
    repositoryClass: AppBundle\Repository\ExerciseTypeRepository
    cache:
        usage: NONSTRICT_READ_WRITE
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            options:
                unsigned: true

    fields:

        name:
            type: string
            length: 255

    oneToMany:
        exercises:
            targetEntity: AppBundle\Entity\Exercise
            mappedBy: exerciseType
            cache:
                usage: NONSTRICT_READ_WRITE
