AppBundle\Entity\MealProductMeta:
    type: entity
    table: meal_product_meta
    repositoryClass: AppBundle\Repository\MealProductMetaRepository
    cache:
        usage: NONSTRICT_READ_WRITE
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            options:
                unsigned: true

    fields:
        lactose:
            type: boolean
            options:
                default: false

        gluten:
            type: boolean
            options:
                default: false

        nuts:
            type: boolean
            options:
                default: false

        eggs:
            type: boolean
            options:
                default: false

        pig:
            type: boolean
            options:
                default: false

        shellfish:
            type: boolean
            options:
                default: false

        fish:
            type: boolean
            options:
                default: false

        notVegetarian:
            type: boolean
            column: not_vegetarian
            options:
                default: false

        notVegan:
            type: boolean
            column: not_vegan
            options:
                default: false

        notPescetarian:
            type: boolean
            column: not_pescetarian
            options:
                default: false

    oneToOne:
        mealProduct:
            targetEntity: AppBundle\Entity\MealProduct
            inversedBy: mealProductMeta
            joinColumn:
                referencedColumnName: id
                onDelete: CASCADE
                nullable: false

    lifecycleCallbacks: {  }
