AppBundle\Entity\WorkoutType:
    type: entity
    table: workout_types
    repositoryClass: AppBundle\Repository\WorkoutTypeRepository
    cache:
        usage: NONSTRICT_READ_WRITE
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            options:
                unsigned: true
    fields:
        name:
            type: string
            length: 255

    lifecycleCallbacks: {  }
